// Pure generators for the files the installer writes. Kept dependency-free and
// separate from the I/O so they are unit-testable.

export interface InstallConfig {
  version: string // image tag to pin (e.g. "0.3.0" or "latest")
  webUrl: string // public URL browsers load the dashboard at
  serverBase: string // public address agents reach the MCP server at
  webPort: string // host port to publish the web UI on
  serverPort: string // host port to publish the MCP server on
  postgresPassword: string
  authSecret: string
  smtp?: {
    host: string
    port: string
    user: string
    pass: string
    from: string
    secure: string
  }
}

/** Generate the self-contained docker-compose.yml for a self-host install. */
export function renderCompose(): string {
  // Values come from the sibling .env (compose interpolates ${...}); the compose
  // file itself carries no secrets, so it is safe to commit/share.
  return `# RelayRoom self-host - generated by @relayroom/install. Prebuilt public images.
#   1. mkdir -p storage && sudo chown -R 1000:1000 storage
#   2. docker compose up -d
# Edit .env to change addresses/ports/SMTP. The server migrates the DB on boot.
services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: \${POSTGRES_USER:-hub}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:?set POSTGRES_PASSWORD in .env}
      POSTGRES_DB: \${POSTGRES_DB:-hub}
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${POSTGRES_USER:-hub}"]
      interval: 5s
      timeout: 3s
      retries: 10

  server:
    image: ghcr.io/relayroom/relayroom-server:\${RELAYROOM_VERSION:-latest}
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://\${POSTGRES_USER:-hub}:\${POSTGRES_PASSWORD}@postgres:5432/\${POSTGRES_DB:-hub}
      PORT: "48801"
    ports:
      - "\${RELAYROOM_SERVER_PORT:-48801}:48801"
    # The server runs DB migrations on boot and only listens afterwards, so a
    # passing /health means migrations are done. web gates on this (service_healthy)
    # to avoid serving against an unmigrated schema.
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://127.0.0.1:48801/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy

  web:
    image: ghcr.io/relayroom/relayroom-web:\${RELAYROOM_VERSION:-latest}
    restart: unless-stopped
    user: "1000:1000"
    environment:
      HUB_API_URL: http://server:48801
      DATABASE_URL: postgres://\${POSTGRES_USER:-hub}:\${POSTGRES_PASSWORD}@postgres:5432/\${POSTGRES_DB:-hub}
      BETTER_AUTH_SECRET: \${BETTER_AUTH_SECRET:?set BETTER_AUTH_SECRET in .env}
      BETTER_AUTH_URL: \${RELAYROOM_PUBLIC_WEB_URL:-http://localhost:48800}
      RELAYROOM_PUBLIC_SERVER_BASE: \${RELAYROOM_PUBLIC_SERVER_BASE:-http://localhost:48801}
      SMTP_HOST: \${SMTP_HOST:-}
      SMTP_PORT: \${SMTP_PORT:-}
      SMTP_USER: \${SMTP_USER:-}
      SMTP_PASS: \${SMTP_PASS:-}
      SMTP_FROM: \${SMTP_FROM:-}
      SMTP_SECURE: \${SMTP_SECURE:-}
      STORAGE_DIR: /app/storage
    volumes:
      - ./storage:/app/storage
    ports:
      - "\${RELAYROOM_WEB_PORT:-48800}:48800"
    depends_on:
      server:
        condition: service_healthy
      postgres:
        condition: service_healthy

volumes:
  pgdata:
`
}

/** Escape a value for a dotenv line: quote when it contains characters that a
 *  naive parser could mishandle (whitespace, #, quotes). Secrets here are
 *  URL-safe (hex/base64) but user-entered SMTP values are unconstrained. */
function envValue(v: string): string {
  if (v === '') return ''
  if (/^[A-Za-z0-9_./:@+=-]+$/.test(v)) return v
  return `"${v.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
}

/** Generate the .env consumed by the compose file. Holds the secrets. */
export function renderEnv(c: InstallConfig): string {
  const lines = [
    '# RelayRoom self-host config - generated by @relayroom/install. Keep this private.',
    '',
    '# Auto-generated secrets (rotate by editing here, then `docker compose up -d`).',
    `POSTGRES_PASSWORD=${envValue(c.postgresPassword)}`,
    `BETTER_AUTH_SECRET=${envValue(c.authSecret)}`,
    '',
    '# Public addresses (how users + remote agents reach this host).',
    `RELAYROOM_PUBLIC_WEB_URL=${envValue(c.webUrl)}`,
    `RELAYROOM_PUBLIC_SERVER_BASE=${envValue(c.serverBase)}`,
    '',
    '# Pinned release (server + web move in lockstep).',
    `RELAYROOM_VERSION=${envValue(c.version)}`,
    `RELAYROOM_WEB_PORT=${envValue(c.webPort)}`,
    `RELAYROOM_SERVER_PORT=${envValue(c.serverPort)}`,
    '',
    '# SMTP for invitation emails (empty = link shown in UI + logged).',
    `SMTP_HOST=${envValue(c.smtp?.host ?? '')}`,
    `SMTP_PORT=${envValue(c.smtp?.port ?? '')}`,
    `SMTP_USER=${envValue(c.smtp?.user ?? '')}`,
    `SMTP_PASS=${envValue(c.smtp?.pass ?? '')}`,
    `SMTP_FROM=${envValue(c.smtp?.from ?? '')}`,
    `SMTP_SECURE=${envValue(c.smtp?.secure ?? '')}`,
    '',
  ]
  return lines.join('\n')
}
