import { execFile, spawn } from "node:child_process"
import { createServer, type Server } from "node:http"
import { mkdtempSync, mkdirSync, rmSync, writeFileSync, existsSync, readFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { fileURLToPath } from "node:url"
import { afterEach, beforeEach, describe, expect, it } from "vitest"
import { init } from "../src/init"

const GUARD = fileURLToPath(new URL("../runtime/relayroom-ask-guard.mjs", import.meta.url))

/**
 * The runtime endpoints now want a bearer. These three callers are on the grace
 * path (the server still accepts them unauthenticated and logs a warning), so both
 * directions matter: the token must be SENT when the worktree has one, so the grace
 * can eventually be withdrawn, and NO header may be sent when it does not - an empty
 * `Bearer ` is a present-but-invalid credential that the server rejects outright.
 */

/** Records the Authorization header of every request, by path. */
function recordingHub(handler?: (path: string) => { status: number; body: string; headers?: Record<string, string> }) {
  const seen: { path: string; auth: string | undefined }[] = []
  const server: Server = createServer((req, res) => {
    const path = (req.url ?? "").split("?")[0] ?? ""
    seen.push({ path, auth: req.headers.authorization })
    const out = handler?.(path) ?? { status: 200, body: "{}" }
    res.writeHead(out.status, { "content-type": "application/json", ...(out.headers ?? {}) })
    res.end(out.body)
  })
  const port = new Promise<number>((resolve) => {
    server.listen(0, "127.0.0.1", () => resolve((server.address() as { port: number }).port))
  })
  return { server, port, seen, authFor: (p: string) => seen.find((s) => s.path === p)?.auth }
}

const MD_HANDLER = () => ({
  status: 200,
  body: "# RELAYROOM.md\n",
  headers: { "x-relayroom-project-slug": "demo" },
})

describe("relayroom init: RELAYROOM.md fetch", () => {
  let dir: string
  let hub: ReturnType<typeof recordingHub>
  let url: string
  let savedTmux: string | undefined

  beforeEach(async () => {
    dir = mkdtempSync(join(tmpdir(), "relayroom-init-"))
    hub = recordingHub(MD_HANDLER)
    url = `http://127.0.0.1:${await hub.port}`
    // init renames the CURRENT tmux session when it runs inside one. The test runner
    // may well be inside tmux, and renaming the developer's own session would be a
    // nasty surprise, so hide it for the duration.
    savedTmux = process.env.TMUX
    delete process.env.TMUX
  })

  afterEach(() => {
    hub.server.close()
    if (savedTmux !== undefined) process.env.TMUX = savedTmux
    rmSync(dir, { recursive: true, force: true })
  })

  it("sends the bearer passed on the command line", async () => {
    await init({ dir, code: "c1", part: "core", server: url, token: "tok-flag", tmuxCheck: false })
    expect(hub.authFor("/mcp/c1/relayroom-md")).toBe("Bearer tok-flag")
  })

  it("sends the token saved by a previous init (the re-init path passes no flags)", async () => {
    await init({ dir, code: "c1", part: "core", server: url, token: "tok-saved", tmuxCheck: false })
    await init({ dir, tmuxCheck: false }) // `relayroom init` with nothing else
    expect(hub.seen.filter((s) => s.path === "/mcp/c1/relayroom-md")).toHaveLength(2)
    expect(hub.seen[1]?.auth).toBe("Bearer tok-saved")
  })

  it("sends no authorization header on a first init, which has no token yet", async () => {
    await init({ dir, code: "c1", part: "core", server: url, tmuxCheck: false })
    expect(hub.authFor("/mcp/c1/relayroom-md")).toBeUndefined()
    expect(existsSync(join(dir, "RELAYROOM.md"))).toBe(true)
  })
})

/** Run a command, resolving with its exit code and output (never rejects). */
function run(cmd: string, args: string[], opts: { cwd?: string } = {}): Promise<{ code: number; stdout: string; stderr: string }> {
  return new Promise((resolve) => {
    execFile(cmd, args, { cwd: opts.cwd, timeout: 20_000 }, (err, stdout, stderr) => {
      const code = err && typeof (err as { code?: unknown }).code === "number" ? (err as { code: number }).code : err ? 1 : 0
      resolve({ code, stdout: String(stdout), stderr: String(stderr) })
    })
  })
}

describe("generated rr.sh: update", () => {
  let dir: string
  let hub: ReturnType<typeof recordingHub>
  let url: string
  let savedTmux: string | undefined

  // rr.sh is generated by init, so this exercises the script that actually ships.
  const initWorktree = async (token?: string) => {
    await init({ dir, code: "c1", part: "core", server: url, token, tmuxCheck: false })
  }

  beforeEach(async () => {
    dir = mkdtempSync(join(tmpdir(), "relayroom-rrsh-"))
    hub = recordingHub(MD_HANDLER)
    url = `http://127.0.0.1:${await hub.port}`
    savedTmux = process.env.TMUX
    delete process.env.TMUX
  })

  afterEach(() => {
    hub.server.close()
    if (savedTmux !== undefined) process.env.TMUX = savedTmux
    rmSync(dir, { recursive: true, force: true })
  })

  it("passes the token to curl when the worktree has one", async () => {
    await initWorktree("tok-rrsh")
    const { code } = await run("bash", [join(dir, "rr.sh"), "update"], { cwd: dir })
    expect(code).toBe(0)
    expect(hub.seen.filter((s) => s.path === "/mcp/c1/relayroom-md").at(-1)?.auth).toBe("Bearer tok-rrsh")
  })

  it("omits the header entirely when there is no token, and still updates", async () => {
    await initWorktree()
    const before = readFileSync(join(dir, "RELAYROOM.md"), "utf8")
    const { code, stderr } = await run("bash", [join(dir, "rr.sh"), "update"], { cwd: dir })
    expect(code, stderr).toBe(0)
    expect(hub.seen.filter((s) => s.path === "/mcp/c1/relayroom-md").at(-1)?.auth).toBeUndefined()
    expect(readFileSync(join(dir, "RELAYROOM.md"), "utf8")).toBe(before)
  })
})

describe("generated rr.sh: statusline unread count", () => {
  let dir: string
  let hub: ReturnType<typeof recordingHub>
  let url: string
  let savedTmux: string | undefined

  beforeEach(async () => {
    dir = mkdtempSync(join(tmpdir(), "relayroom-sl-"))
    // The status bar reads the count out of this shape.
    hub = recordingHub((path) =>
      path.endsWith("/unread")
        ? { status: 200, body: JSON.stringify({ count: 3 }) }
        : MD_HANDLER(),
    )
    url = `http://127.0.0.1:${await hub.port}`
    savedTmux = process.env.TMUX
    delete process.env.TMUX
  })

  afterEach(() => {
    hub.server.close()
    if (savedTmux !== undefined) process.env.TMUX = savedTmux
    rmSync(dir, { recursive: true, force: true })
  })

  it("sends the bearer and renders the count", async () => {
    await init({ dir, code: "c1", part: "core", server: url, token: "tok-sl", tmuxCheck: false })
    const { code, stdout } = await run("bash", [join(dir, "rr.sh"), "statusline"], { cwd: dir })
    expect(code).toBe(0)
    expect(hub.authFor("/mcp/c1/unread")).toBe("Bearer tok-sl")
    expect(stdout).toContain("inbox: 3")
  })

  it("omits the header when there is no token, and the bar still renders", async () => {
    await init({ dir, code: "c1", part: "core", server: url, tmuxCheck: false })
    const { code, stdout } = await run("bash", [join(dir, "rr.sh"), "statusline"], { cwd: dir })
    expect(code).toBe(0)
    expect(hub.authFor("/mcp/c1/unread")).toBeUndefined()
    expect(stdout).toContain("inbox: 3")
  })
})

/**
 * Claude pipes the tool payload into the guard on stdin and the guard drains it
 * before doing anything, so the child needs a stdin that actually ends - an
 * inherited one never closes and the guard would sit there forever.
 */
function runGuard(cwd: string): Promise<{ code: number; stderr: string }> {
  return new Promise((resolve) => {
    const child = spawn(process.execPath, [GUARD], { cwd, stdio: ["pipe", "pipe", "pipe"] })
    let stderr = ""
    child.stderr.on("data", (d) => (stderr += d))
    child.stdout.resume()
    child.stdin.end(JSON.stringify({ tool_name: "AskUserQuestion" }))
    child.on("exit", (code) => resolve({ code: code ?? 0, stderr }))
  })
}

describe("generated rr.sh: update --self", () => {
  let dir: string
  let bin: string
  let hub: ReturnType<typeof recordingHub>
  let url: string
  let savedTmux: string | undefined

  beforeEach(async () => {
    dir = mkdtempSync(join(tmpdir(), "relayroom-self-"))
    bin = mkdtempSync(join(tmpdir(), "relayroom-bin-"))
    hub = recordingHub(MD_HANDLER)
    url = `http://127.0.0.1:${await hub.port}`
    savedTmux = process.env.TMUX
    delete process.env.TMUX
    // A stub `relayroom` that records the argv rr.sh hands it, instead of
    // regenerating the worktree for real.
    writeFileSync(
      join(bin, "relayroom"),
      `#!/bin/sh\nprintf '%s\\n' "$*" >> "${join(dir, "cli-argv.log")}"\nexit 0\n`,
      { mode: 0o755 },
    )
  })

  afterEach(() => {
    hub.server.close()
    if (savedTmux !== undefined) process.env.TMUX = savedTmux
    for (const d of [dir, bin]) rmSync(d, { recursive: true, force: true })
  })

  it("passes the worktree's own agent through, not the claude default", async () => {
    await init({ dir, code: "c1", part: "core", server: url, token: "t", agent: "codex", tmuxCheck: false })
    await new Promise<void>((resolve) => {
      execFile(
        "bash",
        [join(dir, "rr.sh"), "update", "--self"],
        { cwd: dir, env: { ...process.env, PATH: `${bin}:${process.env.PATH}` }, timeout: 20_000 },
        () => resolve(),
      )
    })
    const argv = readFileSync(join(dir, "cli-argv.log"), "utf8")
    // Without --agent, init would default to claude and write a CLAUDE.md into a
    // worktree driven by codex.
    expect(argv).toContain("--agent codex")
  })
})

describe("generated rr.sh: global MCP config takeover warning", () => {
  let dir: string
  let home: string
  let bin: string
  let hub: ReturnType<typeof recordingHub>
  let url: string
  let savedTmux: string | undefined

  beforeEach(async () => {
    dir = mkdtempSync(join(tmpdir(), "relayroom-i1-"))
    home = mkdtempSync(join(tmpdir(), "relayroom-home-"))
    bin = mkdtempSync(join(tmpdir(), "relayroom-bin-"))
    hub = recordingHub(MD_HANDLER)
    url = `http://127.0.0.1:${await hub.port}`
    savedTmux = process.env.TMUX
    delete process.env.TMUX
    // A stub `codex` so the test never runs (or configures) the real one.
    writeFileSync(join(bin, "codex"), "#!/bin/sh\nexit 0\n", { mode: 0o755 })
  })

  afterEach(() => {
    hub.server.close()
    if (savedTmux !== undefined) process.env.TMUX = savedTmux
    for (const d of [dir, home, bin]) rmSync(d, { recursive: true, force: true })
  })

  /** codex keeps ONE machine-global config, with the part baked into the MCP URL. */
  const writeCodexConfig = (part: string) => {
    mkdirSync(join(home, ".codex"), { recursive: true })
    writeFileSync(
      join(home, ".codex", "config.toml"),
      `[mcp_servers.relayroom]\nurl = "http://hub/mcp/c1?part=${part}"\n`,
    )
  }

  const runMcpAdd = (extraEnv: Record<string, string> = {}) =>
    new Promise<{ stdout: string; stderr: string }>((resolve) => {
      execFile(
        "bash",
        [join(dir, "rr.sh"), "codex", "mcp-add"],
        { cwd: dir, env: { ...process.env, HOME: home, PATH: `${bin}:${process.env.PATH}`, ...extraEnv }, timeout: 20_000 },
        (_err, stdout, stderr) => resolve({ stdout: String(stdout), stderr: String(stderr) }),
      )
    })

  it("warns when the global config belongs to another part", async () => {
    await init({ dir, code: "c1", part: "core", server: url, token: "t", agent: "codex", tmuxCheck: false })
    writeCodexConfig("web")
    const { stderr } = await runMcpAdd()
    expect(stderr).toContain("GLOBAL")
    expect(stderr).toContain("'web'")
    expect(stderr).toContain("EVERY codex worktree")
  })

  it("stays quiet when the global config already names this part", async () => {
    await init({ dir, code: "c1", part: "core", server: url, token: "t", agent: "codex", tmuxCheck: false })
    writeCodexConfig("core")
    const { stderr } = await runMcpAdd()
    expect(stderr).not.toContain("GLOBAL")
  })

  it("stays quiet when nothing is registered yet", async () => {
    await init({ dir, code: "c1", part: "core", server: url, token: "t", agent: "codex", tmuxCheck: false })
    const { stderr } = await runMcpAdd()
    expect(stderr).not.toContain("GLOBAL")
  })
})

describe("ask guard: role lookup", () => {
  let dir: string
  let hub: ReturnType<typeof recordingHub>
  let url: string

  const writeConfig = (extra: Record<string, unknown> = {}) => {
    mkdirSync(join(dir, ".relayroom"), { recursive: true })
    writeFileSync(
      join(dir, ".relayroom", "config.json"),
      JSON.stringify({ code: "c1", part: "core", server: url, ...extra }),
    )
  }

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), "relayroom-guard-"))
  })

  afterEach(() => {
    hub.server.close()
    rmSync(dir, { recursive: true, force: true })
  })

  const startHub = async (status: number, role = "default") => {
    hub = recordingHub(() => ({ status, body: JSON.stringify({ role }) }))
    url = `http://127.0.0.1:${await hub.port}`
  }

  it("sends the bearer and still blocks a non-main agent", async () => {
    await startHub(200, "default")
    writeConfig({ token: "tok-guard" })
    const { code, stderr } = await runGuard(dir)
    expect(hub.authFor("/mcp/c1/role")).toBe("Bearer tok-guard")
    expect(code).toBe(2) // blocked
    expect(stderr).toContain("main agent")
  })

  it("sends no header when the worktree has no token", async () => {
    await startHub(200, "main")
    writeConfig()
    const { code } = await runGuard(dir)
    expect(hub.authFor("/mcp/c1/role")).toBeUndefined()
    expect(code).toBe(0) // main -> allowed
  })

  it("fails OPEN on a rejected lookup, but says so on stderr", async () => {
    await startHub(401)
    writeConfig({ token: "stale" })
    const { code, stderr } = await runGuard(dir)
    // Allowing is deliberate: a hub problem must not wedge an agent mid-turn.
    expect(code).toBe(0)
    expect(stderr).toContain("401")
    expect(stderr).toContain("./rr.sh setup")
  })
})

describe("generated rr.sh: session name guard", () => {
  let dir: string
  let hub: ReturnType<typeof recordingHub>
  let url: string
  let savedTmux: string | undefined

  beforeEach(async () => {
    dir = mkdtempSync(join(tmpdir(), "relayroom-target-"))
    hub = recordingHub(MD_HANDLER)
    url = `http://127.0.0.1:${await hub.port}`
    savedTmux = process.env.TMUX
    delete process.env.TMUX
  })

  afterEach(() => {
    hub.server.close()
    if (savedTmux !== undefined) process.env.TMUX = savedTmux
    rmSync(dir, { recursive: true, force: true })
  })

  const runRr = (args: string[]) =>
    new Promise<{ code: number; stdout: string; stderr: string }>((resolve) => {
      execFile(
        "bash",
        [join(dir, "rr.sh"), ...args],
        { cwd: dir, timeout: 20_000 },
        (err, stdout, stderr) => {
          const code = err && typeof (err as { code?: unknown }).code === "number" ? (err as { code: number }).code : err ? 1 : 0
          resolve({ code, stdout: String(stdout), stderr: String(stderr) })
        },
      )
    })

  // A window/pane target in config.target: tmux would silently create a session
  // called "rr-core_0_1" while the pager keeps waking "rr-core:0.1".
  const AMBIGUOUS = "rr-core:0.1"

  it("refuses to touch tmux when the target is a window/pane target", async () => {
    await init({ dir, code: "c1", part: "core", server: url, target: AMBIGUOUS, tmuxCheck: false })
    const { code, stderr } = await runRr(["down"])
    expect(code).toBe(1)
    expect(stderr).toContain("cannot use as a session name")
    // The message has to name the rewrite, or the user cannot connect the symptom
    // (nothing wakes) to the cause (two different session names).
    expect(stderr).toContain("rr-core_0_1")
  })

  it("diagnoses instead of dying in doctor, which is what you run when it bites", async () => {
    await init({ dir, code: "c1", part: "core", server: url, target: AMBIGUOUS, tmuxCheck: false })
    const { stdout } = await runRr(["doctor"])
    expect(stdout).toContain("window/pane separator")
    expect(stdout).toContain("nobody delivers")
  })

  it("stays out of the way for an ordinary session name", async () => {
    await init({ dir, code: "c1", part: "core", server: url, target: "RR-demo-core", tmuxCheck: false })
    const { stderr } = await runRr(["down"])
    expect(stderr).not.toContain("cannot use as a session name")
  })
})
