import { chmodSync, existsSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs"
import { execFileSync } from "node:child_process"
import { join, resolve } from "node:path"
import { DEFAULT_SERVER } from "./constants"
import { RELAYROOM_DIR, writeConfig, readConfig } from "./config"
import { runtimePath } from "./runtime"

/**
 * Register the Claude Channels server in the worktree's `.mcp.json` so Claude can
 * spawn it (and `--dangerously-load-development-channels server:relayroom-channel`
 * can reference it by name). Merges into any existing config, never clobbering other
 * servers. The server is invoked as `node <abs runtime path> --dir <worktree>`, which
 * avoids any PATH / npx dependency and self-recovers identity from .relayroom/config.
 * The server stays DORMANT unless `delivery=channel`, so its presence is harmless
 * under pager delivery. Returns whether the file was newly created.
 */
export function ensureChannelMcp(dir: string): { created: boolean; changed: boolean } {
  const path = join(dir, ".mcp.json")
  const existed = existsSync(path)
  let json: Record<string, unknown> = {}
  if (existed) {
    const raw = readFileSync(path, "utf8")
    try {
      const parsed = JSON.parse(raw) as unknown
      // Must be a JSON OBJECT - an array is `typeof "object"` too, but assigning
      // mcpServers onto it would be dropped by JSON.stringify, silently losing our
      // server. Treat array / primitive / null as malformed and back it up.
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        json = parsed as Record<string, unknown>
      } else {
        throw new Error("not a JSON object")
      }
    } catch {
      // Malformed/non-object .mcp.json: never silently clobber a recoverable file.
      // Preserve the original alongside, warn, then write a fresh merged config. Use
      // EXCLUSIVE create (flag "wx") in a loop so two concurrent inits can't race to
      // the same .bak and overwrite each other's backup.
      let bak = ""
      for (let i = 0; i < 100; i++) {
        const candidate = i === 0 ? `${path}.bak` : `${path}.bak.${i}`
        try { writeFileSync(candidate, raw, { flag: "wx" }); bak = candidate; break } catch { /* exists - try next */ }
      }
      console.warn(bak
        ? `warning: ${path} was malformed; backed it up to ${bak} before writing the channel server`
        : `warning: ${path} was malformed and could not be backed up; overwriting`)
      json = {}
    }
  }
  // Reuse an existing server MAP, but a `mcpServers` that is an array (or any
  // non-object) can't hold our named entry - JSON.stringify would drop it - so start
  // a fresh map in that case.
  const servers = (json.mcpServers && typeof json.mcpServers === "object" && !Array.isArray(json.mcpServers)
    ? (json.mcpServers as Record<string, unknown>)
    : {})
  // Bake the ABSOLUTE node path (process.execPath) so the channel server launches
  // even if `node` is not on the PATH Claude inherits.
  const entry = { command: process.execPath, args: [runtimePath("relayroom-channel.mjs"), "--dir", dir] }
  if (JSON.stringify(servers["relayroom-channel"]) === JSON.stringify(entry)) {
    return { created: false, changed: false }
  }
  servers["relayroom-channel"] = entry
  json.mcpServers = servers
  writeFileSync(path, JSON.stringify(json, null, 2) + "\n")
  return { created: !existed, changed: true }
}

/**
 * `rr.sh` - one control console for everything you do with RelayRoom in a worktree,
 * written into .relayroom/ at init time. Reads .relayroom/config.json (code, part,
 * target session, agent, token), so after a reboot the user runs `./.relayroom/rr.sh
 * up` to rebuild the tmux session + pager, instead of remembering a pile of commands.
 * Covers: tmux (start/continue/exit), pager (start/stop/restart/status), per-CLI
 * mcp-add + hooks (claude/agy/codex), and up/down/status/setup.
 */
const RR_SCRIPT = `#!/usr/bin/env bash
# RelayRoom control console for THIS worktree. Generated by \`relayroom init\`.
set -euo pipefail

ROOT="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"   # worktree root (rr.sh lives here)
cd "$ROOT"
CONF="$ROOT/.relayroom/config.json"
[ -f "$CONF" ] || { echo "no .relayroom/config.json here - run 'relayroom init' first"; exit 1; }

# Load all config fields in ONE node call (statusline runs every few seconds, so
# avoid 6 separate spawns). Fields are slug/url/hex - none contain '|'. PREV is the
# previous session name (if init just renamed it) so up can migrate a live session.
_C="$(node -e 'var c=require(process.argv[1]);process.stdout.write([c.code,c.part,c.server,c.target,c.agent,c.token,c.previousTarget].map(function(x){return String(x||"")}).join("|"))' "$CONF" 2>/dev/null || true)"
IFS='|' read -r CODE PART SERVER SESSION AGENT TOKEN PREV <<< "$_C"
[ -n "$SERVER" ] || SERVER="http://localhost:48801"
[ -n "$SESSION" ] || SESSION="$PART"
PRIMARY="\${AGENT%%,*}"; [ -n "$PRIMARY" ] || PRIMARY="claude"
URL="$SERVER/mcp/$CODE?part=$PART"
PIDFILE="$ROOT/.relayroom/pager.pid"; LOG="$ROOT/.relayroom/pager.log"
CLI="relayroom"; command -v relayroom >/dev/null 2>&1 || CLI="npx -y @relayroom/cli"

# ── launch (Claude Channels premium path vs send-keys) ─────────────────────────
# Decide how to launch the PRIMARY agent and which wake-delivery mode to use. Claude
# gets the Channels path (queued at the turn boundary, no TTY interleaving) when its
# CLI supports --channels (research preview); everything else falls back to the
# pager's send-keys deferral. Sets LAUNCH (the command to run) + writes delivery to
# config so the pager and the channel server agree. Probe is cheap: \`--channels\`
# with no value makes commander print "argument missing" iff the flag exists.
# Opt-in bypass: \`./rr.sh up --bypass\` (or \`./rr.sh claude run --bypass\`) appends the
# primary CLI's "skip approval prompts" launch flag. Detected anywhere in the args.
BYPASS=0; for _a in "$@"; do [ "$_a" = "--bypass" ] && BYPASS=1; done
# Opt-in fresh start: \`./rr.sh up --new\` begins a NEW conversation. WITHOUT --new the
# launched CLI resumes its most recent session for this workdir (so re-launching after a
# reboot keeps context), falling back to a fresh start when there is none. Detected
# anywhere in the args.
NEW=0; for _a in "$@"; do [ "$_a" = "--new" ] && NEW=1; done
# bypass flag for a CLI (defaults to PRIMARY) - so \`<cli> run --bypass\` works for all.
bypass_flag() {
  case "\${1:-$PRIMARY}" in
    claude) echo "--dangerously-skip-permissions" ;;
    agy)    echo "--dangerously-skip-permissions" ;;
    codex)  echo "--dangerously-bypass-approvals-and-sandbox" ;;
  esac
}

# Build the launch command for CLI $1 given its base command $2 (binary + any channel
# flag) and bypass suffix $3. Default resumes the most recent session for this workdir;
# \`--new\` forces a fresh start. Each CLI's resume form is cwd/project-scoped (claude
# --continue, agy --continue, codex resume --last) and the resume form falls back
# to the fresh form (\`resume || fresh\`) so a first launch with no saved session starts
# clean instead of erroring. Run via \`sh -c\` since the result may contain \`||\`.
build_launch() {
  cli="$1"; base="$2"; byp="$3"; resume=""
  # codex launches under the relayroom profile (autonomous agents: no approval prompts
  # or sandbox - the profile file is written in prepare_launch). --profile is a global
  # flag, so it must precede the subcommand and carry into both resume and fresh forms.
  [ "$cli" = "codex" ] && base="codex --profile relayroom"
  if [ "$NEW" = "1" ]; then echo "$base$byp"; return; fi
  case "$cli" in
    claude) resume="$base --continue$byp" ;;
    agy)    resume="$base --continue$byp" ;;
    codex)  resume="$base resume --last$byp" ;;
    *)      echo "$base$byp"; return ;;
  esac
  echo "$resume || $base$byp"
}

LAUNCH="$PRIMARY"
prepare_launch() {
  local mode="pager" probe="" base="$PRIMARY" byp=""
  # Capture the probe to a var FIRST: piping \`claude --channels\` into grep under
  # \`set -o pipefail\` would report claude's intentional nonzero exit and make the
  # \`if\` always false (channels never activate). \`|| true\` keeps the nonzero from
  # tripping \`set -e\`. The flag exists iff commander prints "argument missing".
  if [ "$PRIMARY" = "claude" ]; then
    probe="$(claude --channels 2>&1 || true)"
    if grep -q "argument missing" <<<"$probe"; then
      base="claude --dangerously-load-development-channels server:relayroom-channel"
      mode="channel"
    fi
  fi
  # The pager and channel server MUST agree on the mode; a stale value causes missed
  # wakes (delivery=channel + bare claude => nobody delivers). Fail loud if it can't
  # be written rather than launching with a wrong mode.
  $CLI delivery "$mode" >/dev/null || { echo "rr.sh: failed to set delivery=$mode - aborting launch" >&2; exit 1; }
  # Opt-in: skip the CLI's approval prompts (bypasses ALL permission checks, not just
  # RelayRoom). Carried as a suffix so it composes with the channel + resume flags.
  [ "$BYPASS" = "1" ] && byp=" $(bypass_flag)" && echo "bypass: ON ($(bypass_flag))" >&2
  LAUNCH="$(build_launch "$PRIMARY" "$base" "$byp")"
  if [ "$PRIMARY" = "codex" ]; then
    # codex runs autonomously (no human at its console), so launch under the relayroom
    # profile: approval prompts + sandbox off. codex rejects [profiles.x] inline in
    # config.toml, so the profile lives in its own file. Write it idempotently here so
    # codex --profile relayroom always resolves, even on setups upgraded in place.
    mkdir -p "$HOME/.codex"
    cat > "$HOME/.codex/relayroom.config.toml" <<'RRPROFILE'
# RelayRoom autonomous-agent profile (codex --profile relayroom). Generated by rr.sh.
approval_policy = "never"
sandbox_mode = "danger-full-access"
RRPROFILE
    # codex reads its MCP bearer from RELAYROOM_TOKEN at runtime (bearer_token_env_var;
    # codex has no static-token option for streamable HTTP). tmux does NOT propagate the
    # var into a new pane, so inline the export into the launch command - otherwise the
    # empty Bearer 401s and codex silently drops the relayroom MCP server (no tools).
    # POSIX single-quote escape (' -> '\\'') so a token can't break the quoting or
    # inject shell when sh -c re-parses LAUNCH (tokens are URL-safe today; defense anyway).
    if [ -n "$TOKEN" ]; then
      _qt=\${TOKEN//\\'/\\'\\\\\\'\\'}
      LAUNCH="export RELAYROOM_TOKEN='\$_qt'; \$LAUNCH"
    fi
  fi
  [ "$NEW" = "1" ] && echo "session: NEW" >&2 || echo "session: resume last (--new for fresh)" >&2
  echo "wake delivery: $mode" >&2
}

# ── pager ────────────────────────────────────────────────────────────────────
pg_running() { [ -f "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE")" 2>/dev/null; }
# Reap stray pagers for THIS worktree (cwd == ROOT) that the PIDFILE no longer tracks.
# Orphans accumulate across restarts/crashes: each keeps its SSE subscription and claims
# the part's wake lease, delivering nudges into a dead pane - so the LIVE pager gets
# "no active wake" and the agent only re-wakes on the ~30s heartbeat sweep (it feels
# slow/stuck). Match by cwd so a pager in another worktree is never touched. Best-effort:
# needs pgrep + lsof; degrades to PIDFILE-only behavior when either is missing.
pg_reap_strays() {
  command -v lsof >/dev/null 2>&1 && command -v pgrep >/dev/null 2>&1 || return 0
  # lsof reports the PHYSICAL cwd (symlinks resolved), so compare against ROOT resolved
  # the same way - else a worktree under a symlinked path never matches and nothing reaps.
  local keep="\${1:-0}" pid cmd cwd root_p
  root_p="$(cd "$ROOT" 2>/dev/null && pwd -P)" || root_p="$ROOT"
  for pid in $(pgrep -f "relayroom.*pager" 2>/dev/null); do
    [ "$pid" = "$keep" ] && continue
    # Only an actual pager: its command ENDS with the \`pager\` subcommand. Excludes the
    # agent (codex/claude/agy - argv contains "relayroom" but no trailing "pager") and any
    # short-lived \`rr.sh pager <sub>\` call. The \`|| cmd=\`/\`|| cwd=\` fallbacks keep a
    # racing ps/lsof failure (pid vanished mid-loop) from aborting pg_start under set -e.
    cmd="$(ps -o command= -p "$pid" 2>/dev/null)" || cmd=""
    case "$cmd" in *" pager") ;; *) continue ;; esac
    cwd="$(lsof -a -p "$pid" -d cwd -Fn 2>/dev/null | sed -n 's/^n//p')" || cwd=""
    [ "$cwd" = "$root_p" ] && kill "$pid" 2>/dev/null && echo "reaped stray pager (pid $pid)"
  done
  return 0   # never let a non-matching last iteration fail pg_start under set -e
}
pg_start() {
  # Kill untracked strays for this worktree first (keep the PIDFILE pid if still alive),
  # so re-launching can never leave two pagers racing for the same part's wake lease.
  pg_reap_strays "$(cat "$PIDFILE" 2>/dev/null || echo 0)"
  if pg_running; then echo "pager already running (pid $(cat "$PIDFILE"))"; return 0; fi
  nohup $CLI pager >"$LOG" 2>&1 &
  echo $! > "$PIDFILE"; echo "pager started (pid $!) -> $LOG"
}
pg_stop() { if pg_running; then kill "$(cat "$PIDFILE")" && echo "pager stopped"; else echo "pager not running"; fi; rm -f "$PIDFILE"; }
pg_status() { pg_running && echo "pager: running (pid $(cat "$PIDFILE"))" || echo "pager: stopped"; }
# MCP/server reachability, throttled: an actual probe at most every 20s (cached),
# so the 5s status refresh never hammers the server. Any HTTP response (even 404)
# means reachable. 1s timeout so an unreachable server doesn't stall the bar.
mcp_online() {
  local cache="$ROOT/.relayroom/.srvcheck" now ts res
  now="$(date +%s)"
  if [ -f "$cache" ]; then
    read -r ts res < "$cache" 2>/dev/null || { ts=0; res=0; }
    if [ "$(( now - \${ts:-0} ))" -lt 20 ]; then [ "\${res:-0}" = "1" ]; return; fi
  fi
  if curl -s -o /dev/null --max-time 1 "$SERVER/" 2>/dev/null; then res=1; else res=0; fi
  printf '%s %s' "$now" "$res" > "$cache" 2>/dev/null || true
  [ "$res" = "1" ]
}

# Open-unread count for this part, throttled (cache ~4s) so the bar can refresh
# every few seconds without hammering the server. Connect-code trust (no token).
# Excludes closed/canceled threads server-side = "messages still needing attention".
# On any error keep the last cached value (the bar should not flap to 0 on a blip).
unread_count() {
  [ -n "$CODE" ] || { echo 0; return; }
  local cache="$ROOT/.relayroom/.unreadcheck" now ts last val
  now="$(date +%s)"; ts=0; last=0
  if [ -f "$cache" ]; then read -r ts last < "$cache" 2>/dev/null || { ts=0; last=0; }; fi
  # Fresh enough: reuse the cached value (one fetch per ~4s at most).
  if [ "$(( now - \${ts:-0} ))" -lt 4 ]; then echo "\${last:-0}"; return; fi
  # \`|| true\` so a failed curl/grep pipeline under \`set -o pipefail\` doesn't abort
  # rr.sh; an empty result falls through to the keep-last-value line below.
  val="$(curl -s --max-time 1 "$SERVER/mcp/$CODE/unread?part=$PART" 2>/dev/null | grep -o '"count":[0-9]*' | head -1 | grep -o '[0-9]*' || true)"
  # On a failed/empty fetch, keep the last known value (don't flap to 0 on a blip).
  [ -n "$val" ] || val="\${last:-0}"
  printf '%s %s' "$now" "$val" > "$cache" 2>/dev/null || true
  echo "$val"
}

# One-liner for the tmux status bar: <part> | inbox: N | <MCP> | <Pager>. The agent's
# color is the BAR background (the pager sets status-style per session), so the part
# text just rides the bar's readable fg. A live dot is green; offline is red + a "!".
# inbox: N is the open-unread count - highlighted when >0 so a user holding the chat
# window sees there is something to handle; dim when 0.
sl() {
  # upd="" is initialized (not just declared): it is only ASSIGNED when a CLI update
  # is pending (.relayroom/.update exists), so without this an up-to-date install
  # hits \`set -u\` ("upd: unbound variable") when tmux runs the statusline - the bar
  # then shows only the clock. Bash version dependent, so it bit Linux/tmux first.
  local sep mcp pgr inbox n upd=""
  sep="#[fg=colour240]│#[default]"
  n="$(unread_count)"
  if [ "\${n:-0}" -gt 0 ] 2>/dev/null; then inbox="#[fg=yellow,bold]inbox: \${n}#[default]"; else inbox="#[fg=colour244]inbox: 0#[default]"; fi
  if mcp_online; then mcp="#[fg=green]●#[default] MCP"; else mcp="#[fg=red,bold]○ !MCP#[default]"; fi
  if pg_running;  then pgr="#[fg=green]●#[default] Pager"; else pgr="#[fg=red,bold]○ !Pager#[default]"; fi
  # CLI update available: the pager writes the latest npm version into this file.
  # Shows '↑<ver>'; run './rr.sh update' to refresh RELAYROOM.md (npm for the CLI).
  if [ -f "$ROOT/.relayroom/.update" ]; then upd=" $sep #[fg=cyan,bold]↑$(cat "$ROOT/.relayroom/.update" 2>/dev/null)#[default]"; fi
  printf '%s %s %s %s %s %s %s%s' "$PART" "$sep" "$inbox" "$sep" "$mcp" "$sep" "$pgr" "$upd"
}

# ── tmux ─────────────────────────────────────────────────────────────────────
tx_exists() { tmux has-session -t "=$SESSION" 2>/dev/null; }
tx_start() {
  if tx_exists; then echo "session '$SESSION' exists - attaching"; tmux attach -t "=$SESSION";
  else prepare_launch; echo "creating session '$SESSION' running '$LAUNCH'"; tmux new-session -s "$SESSION" "$LAUNCH"; fi
}
tx_status() { tx_exists && echo "tmux: session '$SESSION' running" || echo "tmux: no session '$SESSION'"; }

# Migrate a renamed session: if init recorded a previous name (PREV) and that old
# session is still running while the new name is free, rename it in place. The
# agent keeps running - only the label changes - so a naming-convention change
# rolls out with no manual \`tmux rename-session\` and no recreating the session.
migrate_session_name() {
  [ -n "$PREV" ] && [ "$PREV" != "$SESSION" ] || return 0
  if tmux has-session -t "=$PREV" 2>/dev/null && ! tx_exists; then
    tmux rename-session -t "=$PREV" "$SESSION" 2>/dev/null && echo "renamed session: $PREV -> $SESSION"
  fi
}

# If the hub flagged a newer CLI (the pager writes .relayroom/.update), upgrade
# before launching so \`up\` never runs a stale rr.sh. Best-effort: a failed upgrade
# (e.g. a global install needing sudo) prints a note and continues on the current
# version - it never blocks the launch. On success it regenerates rr.sh and re-execs
# it once (guarded by RR_SELF_UPDATED) so the rest of \`up\` runs the fresh script.
self_update_if_pending() {
  [ -f "$ROOT/.relayroom/.update" ] && [ -z "\${RR_SELF_UPDATED:-}" ] || return 0
  echo "rr: CLI update available ($(cat "$ROOT/.relayroom/.update" 2>/dev/null)) - updating before launch..."
  if command -v relayroom >/dev/null 2>&1; then
    npm i -g @relayroom/cli@latest >/dev/null 2>&1 || echo "rr: could not update the global CLI (continuing on the current version)"
  else
    # npx path: drop the cached package so the next npx resolves the latest version.
    for _d in "$HOME"/.npm/_npx/*/; do [ -e "$_d/node_modules/@relayroom/cli/package.json" ] && rm -rf "$_d" 2>/dev/null || true; done
  fi
  # Regenerate rr.sh + config from the (now-current) CLI, then re-exec the new script.
  $CLI init --code "$CODE" --part "$PART" --server "$SERVER" --no-tmux-check >/dev/null 2>&1 || true
  export RR_SELF_UPDATED=1
  exec "$ROOT/rr.sh" "$@"
}

# ── per-CLI setup (mcp registration + usage hook) ─────────────────────────────
mcp_add() {
  local a="$1"
  [ -n "$TOKEN" ] || { echo "no token in config - reconnect from the dashboard to issue one"; return 1; }
  if [ "$a" = "codex" ]; then
    export RELAYROOM_TOKEN="$TOKEN"
    codex mcp remove relayroom 2>/dev/null || true
    # Codex config is global (~/.codex/config.toml) - no project scope, so all codex
    # worktrees share this entry. Per-worktree part identity is not possible here.
    codex mcp add relayroom --url "$URL" --bearer-token-env-var RELAYROOM_TOKEN
  elif [ "$a" = "agy" ]; then
    # agy (Antigravity, replaced the now-shut-down Gemini CLI) has no \`mcp add\`
    # command - it reads ~/.gemini/config/mcp_config.json. Merge the relayroom server
    # in (preserving any other servers). Token via env so it never lands in shell
    # history. This is a GLOBAL file - like codex, all agy worktrees share this entry,
    # so per-worktree part identity is not possible here.
    RELAYROOM_TOKEN="$TOKEN" node -e 'const fs=require("fs"),os=require("os"),path=require("path");if(!process.env.RELAYROOM_TOKEN){console.error("agy MCP: RELAYROOM_TOKEN not set");process.exit(1)}const p=path.join(os.homedir(),".gemini","config","mcp_config.json");fs.mkdirSync(path.dirname(p),{recursive:true});let c={};try{c=JSON.parse(fs.readFileSync(p,"utf8")||"{}")}catch(e){}c.mcpServers=c.mcpServers||{};c.mcpServers.relayroom={url:process.argv[1],headers:{Authorization:"Bearer "+process.env.RELAYROOM_TOKEN}};fs.writeFileSync(p,JSON.stringify(c,null,2))' "$URL"
  else
    # Claude defaults to LOCAL scope, which it keys to the git REPO ROOT - so every
    # worktree shares one entry and they all post as the same part. Register in
    # PROJECT scope (.mcp.json, per-worktree) for per-worktree identity, and drop any
    # old shared local entry so the migration takes effect.
    claude mcp remove relayroom -s local 2>/dev/null || true
    claude mcp remove relayroom -s project 2>/dev/null || true
    claude mcp add -s project --transport http relayroom "$URL" --header "Authorization: Bearer $TOKEN"
  fi
  echo "registered relayroom MCP for $a"
}
hooks_install() { $CLI hooks install --agent "$1"; }
setup() { local a; IFS=',' read -ra _AS <<< "$AGENT"; for a in "\${_AS[@]}"; do mcp_add "$a" && hooks_install "$a"; done; }

# ── doctor: diagnose common setup problems + print the exact fix command ───────
# The #1 support issue is the git-worktree identity tangle: agents in different
# worktrees all post as the same part because the MCP server was registered in
# Claude's repo-root-keyed LOCAL scope instead of the per-worktree project scope.
# doctor() catches that (and token/server/pager gaps) and prints what to run.
doctor() {
  # Conventional CLI coloring: green ok / yellow WARN / red ERR, but only when stdout
  # is a terminal (so piping doctor into a file or grep stays clean). tput avoids
  # hardcoding ANSI escapes; it emits nothing when the terminal has no color.
  local _g="" _y="" _r="" _n=""
  if [ -t 1 ]; then
    _g="$(tput setaf 2 2>/dev/null || true)"; _y="$(tput setaf 3 2>/dev/null || true)"
    _r="$(tput setaf 1 2>/dev/null || true)"; _n="$(tput sgr0 2>/dev/null || true)"
  fi
  local OKM="  \${_g}ok\${_n}  " WRN="  \${_y}WARN\${_n}" ERR="  \${_r}ERR\${_n} "
  echo "RelayRoom doctor - worktree: $ROOT"
  echo "  agent=$AGENT  part=$PART  session=$SESSION"
  local ver; ver="$($CLI --version 2>/dev/null | head -1 || true)"
  echo "$OKM CLI version: \${ver:-unknown}  (per-worktree identity needs 0.3.10+)"
  [ -n "$CODE" ] && echo "$OKM connect code present" || echo "$ERR no connect code - run: relayroom init --code <code> --part $PART"
  [ -n "$TOKEN" ] && echo "$OKM auth token present" || echo "$WRN no token - reconnect from the dashboard to issue one"
  # MCP registration + identity, read from each agent's own config location.
  # claude = per-worktree .mcp.json (project scope). agy/codex use a GLOBAL config
  # file, so all their worktrees share ONE entry (whichever ran setup last wins) -
  # a part mismatch there means another worktree owns the global entry.
  local cfgfile cfgdesc global=""
  case "$PRIMARY" in
    claude) cfgfile=".mcp.json"; cfgdesc="this worktree's .mcp.json" ;;
    agy)    cfgfile="$HOME/.gemini/config/mcp_config.json"; cfgdesc="~/.gemini/config/mcp_config.json"; global=1 ;;
    codex)  cfgfile="$HOME/.codex/config.toml"; cfgdesc="~/.codex/config.toml"; global=1 ;;
  esac
  local rp; rp="$(grep -oE 'part=[A-Za-z0-9_-]+' "$cfgfile" 2>/dev/null | head -1 | cut -d= -f2 || true)"
  if [ -n "$rp" ]; then
    echo "$OKM $PRIMARY relayroom MCP registered ($cfgdesc, part=$rp)"
    if [ "$rp" != "$PART" ]; then
      if [ -n "$global" ]; then
        echo "$WRN   registered part ($rp) != this worktree ($PART). $PRIMARY's MCP config is GLOBAL, so another worktree set it last."
        echo "       Re-run ./rr.sh setup here to switch it (or use claude for true per-worktree identity)."
      else
        echo "$WRN   .mcp.json part ($rp) != config part ($PART) - re-run: ./rr.sh setup"
      fi
    fi
  elif [ "$PRIMARY" = "claude" ]; then
    echo "$WRN claude relayroom MCP not in this worktree's .mcp.json - likely sharing the repo-root local scope."
    echo "       If worktrees post as the same part, run:  claude mcp remove relayroom -s local && ./rr.sh setup"
  else
    echo "$WRN $PRIMARY relayroom MCP not registered ($cfgdesc) - run: ./rr.sh setup"
  fi
  [ -n "$global" ] && echo "       note: $PRIMARY MCP config is GLOBAL - worktrees can't hold separate identities here (use claude for that)."
  if mcp_online; then echo "$OKM server reachable ($SERVER)"; else echo "$ERR server UNREACHABLE ($SERVER) - is the hub up?"; fi
  pg_running && echo "$OKM pager running (pid $(cat "$PIDFILE"))" || echo "$WRN pager stopped - start with: ./rr.sh up"
  tx_exists && echo "$OKM tmux session '$SESSION' running" || echo "$WRN no tmux session '$SESSION' - run: ./rr.sh up"
}

usage() {
  cat <<EOF
RelayRoom console (part=$PART, session=$SESSION, agent=$AGENT)
  rr.sh up [--bypass] [--new]    auto-update if a newer CLI is out, then rebuild
                                 session + start pager + attach (after reboot)
  rr.sh launch [--bypass] [--new]  from INSIDE a session: set delivery + pager + run the agent
  rr.sh down                     stop pager + kill the tmux session
  rr.sh status                   show tmux + pager status
  rr.sh info                     print resolved config
  rr.sh tmux start|continue|exit|status
  rr.sh pager start|stop|restart|status
  rr.sh headless [stop|status]   codex/agy only: run this part headless (pager spawns the CLI per wake, no tmux)
  rr.sh claude|agy|codex mcp-add|hooks|run [--bypass]
  rr.sh setup                    mcp-add + hooks for every configured agent
  rr.sh doctor                   diagnose setup problems (identity, token, server) + show fixes
  rr.sh update [--self]          re-pull RELAYROOM.md from the hub (--self also regenerates rr.sh)
  rr.sh --version                print the RelayRoom CLI version
  --bypass                       launch the CLI with its skip-all-approvals flag
  --new                          start a FRESH conversation (default resumes the last session)
EOF
}

case "\${1:-help}" in
  up)
    self_update_if_pending "$@"   # auto-update first if the hub flagged a newer CLI (may re-exec)
    migrate_session_name          # rename a still-running old-named session to the standard name
    if ! tx_exists; then prepare_launch; echo "starting session '$SESSION' running '$LAUNCH'"; tmux new-session -d -s "$SESSION" "$LAUNCH"; fi
    # RESTART the pager (not just start): a pager left over from a previous session
    # has the OLD target baked in (it reads config.json once at startup and has no
    # --target), so a bare pg_start would no-op on the stale pager and the new
    # session would get no status color / wake delivery. Stop + start re-reads config.
    pg_stop >/dev/null 2>&1 || true; pg_start; echo "attaching ('Ctrl-b d' to detach)"
    # Inside another tmux session, \`attach\` is refused (nesting) - switch the client
    # instead so \`up\` also works from within tmux.
    if [ -n "\${TMUX:-}" ]; then tmux switch-client -t "=$SESSION"; else tmux attach -t "=$SESSION"; fi ;;
  # In-session launcher (you are ALREADY inside the tmux session, e.g. the connect
  # guide's paste). Decides delivery (channel vs pager), starts the pager with that
  # mode, then replaces this shell with the agent - all in the right order so channels
  # actually activate. \`up\` is the from-outside equivalent that also creates+attaches.
  # RESTART the pager (not just start): prepare_launch may have CHANGED delivery
  # (channel<->pager), but the pager only reads delivery at startup, so a stale
  # running pager would deliver in the wrong mode.
  launch) prepare_launch; pg_stop >/dev/null 2>&1 || true; pg_start; exec sh -c "$LAUNCH" ;;
  down) pg_stop; tmux kill-session -t "$SESSION" 2>/dev/null && echo "killed session '$SESSION'" || echo "no session to kill" ;;
  status)
    tx_status
    if mcp_online; then echo "mcp: server reachable ($SERVER)"; else echo "mcp: server UNREACHABLE ($SERVER) - is the hub up?"; fi
    pg_status ;;
  info) echo "code=$CODE part=$PART session=$SESSION agent=$AGENT server=$SERVER token=\${TOKEN:+set}" ;;
  doctor) doctor ;;
  # Print the RelayRoom CLI version (delegates to the installed CLI, so it reflects
  # the current install - run \`./rr.sh update --self\` to regenerate rr.sh after upgrading).
  --version|-v|version) $CLI --version ;;
  tmux) case "\${2:-}" in
      start) tx_start ;; continue|attach) tmux attach -t "$SESSION" ;;
      exit|stop|kill) tmux kill-session -t "$SESSION" && echo "killed '$SESSION'" ;;
      status) tx_status ;; *) usage; exit 1 ;; esac ;;
  pager) case "\${2:-}" in
      start) pg_start ;; stop) pg_stop ;; restart) pg_stop; pg_start ;; status) pg_status ;;
      *) usage; exit 1 ;; esac ;;
  # Opt-in HEADLESS mode (codex/agy only). No tmux session and no interactive agent:
  # the pager spawns the CLI once per wake to process the inbox via the RelayRoom MCP
  # tools. Sets delivery=headless in config, then (re)starts the pager in that mode.
  # \`up\` is untouched and unchanged; this is a separate path a part opts into. Roll back
  # to interactive send-keys with: rr.sh pager stop; $CLI delivery pager; rr.sh up.
  headless) case "\${2:-start}" in
      start|"")
        case "\${AGENT%%,*}" in codex|agy) ;; *) echo "rr.sh headless: only codex/agy parts support this (agent=$AGENT)" >&2; exit 1 ;; esac
        $CLI delivery headless >/dev/null || { echo "rr.sh: failed to set delivery=headless - aborting" >&2; exit 1; }
        pg_stop >/dev/null 2>&1 || true; pg_start
        echo "headless ON: wakes spawn '\${AGENT%%,*}' per message (no tmux). Roll back: rr.sh pager stop; $CLI delivery pager; rr.sh up" ;;
      stop) pg_stop ;; status) pg_status ;;
      *) usage; exit 1 ;; esac ;;
  claude|agy|codex) case "\${2:-}" in
      mcp-add) mcp_add "$1" ;; hooks) hooks_install "$1" ;;
      run)
        # claude routes through prepare_launch (channel flag + bypass + resume). agy/codex
        # have no channel path, but STILL honor --bypass (their own flag) and --new/resume.
        if [ "$1" = "claude" ]; then prepare_launch; exec sh -c "$LAUNCH"
        else
          byp=""; [ "$BYPASS" = "1" ] && byp=" $(bypass_flag "$1")"
          exec sh -c "$(build_launch "$1" "$1" "$byp")"
        fi ;;
      *) usage; exit 1 ;; esac ;;
  setup) setup ;;
  # Refresh the agent-side files in place (run from INSIDE the agent, e.g. \`! ./rr.sh update\`).
  update) case "\${2:-}" in
      --self)
        # Also regenerate rr.sh itself via the installed CLI. To get a newer rr.sh,
        # update the CLI on npm first (the \`↑<ver>\` status marker shows when one is out).
        # --no-tmux-check: regenerating rr.sh is maintenance, not launching the agent,
        # so it must work from anywhere (you usually update AFTER exiting tmux). The
        # tmux guard only matters for first-time \`relayroom init\`, which keeps it.
        $CLI init --code "$CODE" --part "$PART" --server "$SERVER" --no-tmux-check ;;
      *)
        # Re-pull just RELAYROOM.md from the hub - no npm needed (the CLI updates via
        # npm). The running agent caches the old copy, so re-read it afterwards.
        if curl -fsS "$SERVER/mcp/$CODE/relayroom-md" -o "$ROOT/RELAYROOM.md"; then
          rm -f "$ROOT/.relayroom/.update" 2>/dev/null || true
          echo "RELAYROOM.md updated from the hub. Re-read it now - the running agent still has the old copy."
        else echo "rr.sh: failed to fetch RELAYROOM.md from $SERVER" >&2; exit 1; fi ;;
    esac ;;
  statusline) sl ;;
  help|-h|--help) usage ;;
  *) usage; exit 1 ;;
esac
`;

/** Per-agent instruction file each coding CLI loads on startup. */
const INSTRUCTION_FILES: Record<string, string> = {
  claude: "CLAUDE.md",
  codex: "AGENTS.md",
  // agy (Antigravity) reads the ~/.gemini config root, so it keeps GEMINI.md.
  agy: "GEMINI.md",
}

export interface InitOpts {
  code?: string
  part?: string
  target?: string
  server?: string
  dir?: string
  /** Coding CLI being connected - picks which instruction file to wire. May be a
   *  comma list ("claude,codex") for a multi-CLI worktree. */
  agent?: string
  /** Bearer token, saved to config so rr.sh can re-run `mcp add` after a reset. */
  token?: string
  /** false to skip adding the @RELAYROOM.md reference to the instruction file. */
  reference?: boolean
  /** false to skip the "must be inside tmux" guard (commander --no-tmux-check). */
  tmuxCheck?: boolean
}

/**
 * The pager wakes the agent by sending keystrokes to its tmux pane, so the agent
 * (and this setup) must run inside tmux. Block early with guidance unless the
 * caller explicitly bypassed the check. Returns when it is safe to proceed.
 */
function assertInsideTmux(opts: InitOpts): void {
  if (opts.tmuxCheck === false || process.env.TMUX) return
  const part = opts.part ?? "agent"
  console.error(
    [
      "error: not inside a tmux session.",
      "",
      "RelayRoom delivers messages by sending keystrokes to your agent's tmux pane,",
      "so the agent must run inside tmux. Create a session and re-run inside it:",
      "",
      `  tmux new -s relayroom-${part}`,
      "",
      "Then, inside that tmux session, run your agent and the relayroom commands.",
      "(advanced: pass --no-tmux-check to skip this guard.)",
    ].join("\n"),
  )
  process.exit(1)
}

/**
 * When init runs inside the agent's tmux session, rename that session to `target`
 * (the standard RR-<slug>-<part> name) if it differs - so a naming change applies
 * with no manual `tmux rename-session`. Best-effort: skipped when not in tmux, the
 * name already matches, tmux is unavailable, or a session named `target` already
 * exists (never clobber a different session).
 */
function alignTmuxSessionName(target: string): void {
  if (!process.env.TMUX) return
  try {
    const current = execFileSync("tmux", ["display-message", "-p", "#S"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim()
    if (!current || current === target) return
    // A session already named `target` means renaming would collide - leave both be.
    try {
      execFileSync("tmux", ["has-session", "-t", `=${target}`], { stdio: "ignore" })
      return
    } catch { /* no such session - the name is free */ }
    execFileSync("tmux", ["rename-session", "-t", `=${current}`, target], { stdio: "ignore" })
    console.log(`renamed tmux session: ${current} -> ${target}`)
  } catch { /* tmux not available - leave the session name as-is */ }
}

/**
 * Append `line` to a file if it is not already present (one line per check).
 * `create` controls whether a missing file is created. Returns what happened.
 */
function ensureLine(
  path: string,
  line: string,
  { comment, create }: { comment?: string; create?: boolean },
): "added" | "present" | "skipped" {
  const exists = existsSync(path)
  if (!exists && !create) return "skipped"
  const body = exists ? readFileSync(path, "utf8") : ""
  if (body.split(/\r?\n/).some((l) => l.trim() === line)) return "present"
  const sep = body.length === 0 ? "" : body.endsWith("\n") ? "\n" : "\n\n"
  const block = (comment ? `${comment}\n` : "") + line + "\n"
  writeFileSync(path, body + sep + block)
  return "added"
}

/**
 * Materialize RELAYROOM.md into a worktree: pull it from the hub (the dashboard
 * is the source of truth), gitignore it (it is generated/synced local config),
 * and reference it from CLAUDE.md / AGENTS.md with one `@RELAYROOM.md` line.
 */
export async function init(opts: InitOpts): Promise<void> {
  // Guard: must run inside tmux so the pager can wake this agent. Blocks unless
  // --no-tmux-check. When inside tmux, default the pager target to this session.
  assertInsideTmux(opts)

  const dir = resolve(opts.dir ?? ".")
  // Identity resolves explicit flag -> previously-saved config, so a re-init in an
  // existing worktree needs NO flags (e.g. `! relayroom init` from inside the agent
  // to re-pull RELAYROOM.md). writeConfig merges, so omitted fields keep their value.
  const saved = readConfig(dir)
  const code = opts.code ?? saved.code
  if (!code) {
    console.error(
      "error: --code is required the first time. After that, run `relayroom init` in a\n" +
      "worktree that already has .relayroom/config.json and it reuses the saved code/part/server.",
    )
    process.exit(1)
  }
  const part = opts.part ?? saved.part
  // Resolve the server: explicit --server -> previously-saved config -> built-in default.
  const server = (opts.server ?? saved.server ?? DEFAULT_SERVER).replace(/\/$/, "")
  const url = `${server}/mcp/${encodeURIComponent(code)}/relayroom-md`

  let content: string
  let slugHeader: string | undefined
  try {
    const res = await fetch(url)
    if (!res.ok) throw new Error(`server responded ${res.status}`)
    content = await res.text()
    slugHeader = res.headers.get("x-relayroom-project-slug") ?? undefined
  } catch (err) {
    console.error(`error: could not fetch RELAYROOM.md from ${url}: ${(err as Error).message}`)
    process.exit(1)
  }

  const file = join(dir, "RELAYROOM.md")
  writeFileSync(file, content)
  console.log(`wrote ${file}`)

  if (ensureLine(join(dir, ".gitignore"), "RELAYROOM.md", {
    create: true,
    comment: "# RelayRoom (synced from the hub; do not commit)",
  }) === "added") {
    console.log("gitignored RELAYROOM.md")
  }

  // Name the tmux session deterministically as RR-<slug>-<part> so every part on
  // every machine reads "RelayRoom, project, agent" at a glance. An explicit
  // --target always wins; otherwise the hub's project slug drives the name, with a
  // cached slug or the legacy relayroom-<part> as fallbacks if the hub is silent.
  // Sanitize the auto-generated name: tmux session names cannot contain '.', ':',
  // or whitespace, and a slug created outside the web form (e.g. via a bootstrap
  // helper) is not guaranteed clean. Collapse anything else to '-'.
  const tmuxSafe = (s: string) => s.replace(/[^A-Za-z0-9_-]/g, "-")
  const projectSlug = slugHeader ?? saved.projectSlug
  const target =
    opts.target ??
    (projectSlug && part
      ? `RR-${tmuxSafe(projectSlug)}-${tmuxSafe(part)}`
      : saved.target ?? (part ? `relayroom-${tmuxSafe(part)}` : undefined))
  if (!opts.target && target) console.log(`tmux session / pager target: ${target}`)

  // Record the prior name when the target changes so rr.sh can auto-rename a
  // still-running session from the old name to the new one (zero manual steps).
  const previousTarget = saved.target && target && saved.target !== target ? saved.target : undefined

  // Write the machine-local connection identity so the pager, usage hook, and a
  // compacted agent can recover it without re-passing flags. gitignore it.
  const configFile = writeConfig(dir, {
    code,
    part,
    target,
    previousTarget,
    projectSlug,
    server,
    agent: opts.agent,
    token: opts.token,
  })
  console.log(`wrote ${configFile}`)
  if (ensureLine(join(dir, ".gitignore"), `${RELAYROOM_DIR}/`, { create: true }) === "added") {
    console.log(`gitignored ${RELAYROOM_DIR}/`)
  }

  // If init is running inside the agent's own tmux session and its name doesn't
  // match the standard target, rename it in place so the convention applies
  // without recreating the session. Best-effort: no tmux, or a name clash with an
  // existing target session, is silently skipped (rr.sh's migrate step is the
  // from-outside equivalent).
  if (target) alignTmuxSessionName(target)

  // rr.sh control console: one entry point for tmux + pager + per-CLI setup, so a
  // reboot is just `./rr.sh up`. Lives at the worktree ROOT next to RELAYROOM.md
  // (short to type) and is gitignored like RELAYROOM.md.
  const rrScript = join(dir, "rr.sh")
  // Write atomically (temp + rename). `./rr.sh update --self` regenerates rr.sh WHILE
  // bash is still executing it; an in-place writeFileSync truncates+rewrites the SAME
  // inode, so the running shell keeps reading from its old byte offset into the new
  // (longer) content and dies with a syntax error. A rename puts the new content on a
  // fresh inode and leaves the running shell's open handle on the original file.
  const rrTmp = `${rrScript}.tmp`
  writeFileSync(rrTmp, RR_SCRIPT)
  chmodSync(rrTmp, 0o755)
  renameSync(rrTmp, rrScript)
  if (ensureLine(join(dir, ".gitignore"), "rr.sh", { create: true }) === "added") {
    console.log("gitignored rr.sh")
  }
  // Drop earlier copies a previous init may have left under .relayroom/.
  for (const old of ["rr.sh", "pager.sh"]) {
    try { rmSync(join(dir, RELAYROOM_DIR, old)) } catch { /* none */ }
  }
  console.log(`wrote ${rrScript} (run \`./rr.sh up\` to restore the session + pager)`)

  // Register the Claude Channels server in .mcp.json (premium wake path). Only
  // gitignore it when WE created the file: an absolute runtime path is machine-local,
  // but a pre-existing .mcp.json may be tracked with the user's other servers, so we
  // merge in place and leave their VCS choice alone.
  const mcp = ensureChannelMcp(dir)
  if (mcp.changed) {
    console.log(mcp.created ? "wrote .mcp.json (relayroom-channel server)" : "registered relayroom-channel in .mcp.json")
  }
  if (mcp.created && ensureLine(join(dir, ".gitignore"), ".mcp.json", { create: true }) === "added") {
    console.log("gitignored .mcp.json")
  }

  if (opts.reference !== false) {
    // Each coding CLI loads its own instruction file. --agent may be a comma list
    // (e.g. "claude,codex,agy") when one worktree is driven by several CLIs in
    // rotation - wire @RELAYROOM.md into each of their files (creating any the
    // project lacks, else that CLI never sees RELAYROOM.md), then also reference it
    // from any OTHER instruction file that already exists.
    const agentList = (opts.agent ?? "claude")
      .split(",")
      .map((a) => a.trim().toLowerCase())
      .filter(Boolean)
    const selected = [...new Set(agentList.map((a) => INSTRUCTION_FILES[a]).filter(Boolean))]
    if (selected.length === 0) selected.push(INSTRUCTION_FILES.claude)

    for (const file of selected) {
      const path = join(dir, file)
      const existed = existsSync(path)
      if (
        ensureLine(
          path,
          "@RELAYROOM.md",
          existed ? { create: true } : { create: true, comment: "# Project agent instructions" },
        ) === "added"
      ) {
        console.log(existed ? `referenced @RELAYROOM.md in ${file}` : `created ${file} referencing @RELAYROOM.md`)
      }
    }
    for (const name of Object.values(INSTRUCTION_FILES)) {
      if (selected.includes(name)) continue
      if (ensureLine(join(dir, name), "@RELAYROOM.md", { create: false }) === "added") {
        console.log(`referenced @RELAYROOM.md in ${name}`)
      }
    }
  }
}
